person = input("Give me a person's name ")
adperson = input("Give me a adjective describing a person ")
adjective = input("Give me an adjective ")
verb = input("Give me a verb ")
noun = input("Give me a noun ")
verb2 = input("Give me another verb ")
pronoun = input("Give me a peronsal pronoun ")
verb3 = input("GIve me one last verb ")
print("Here is your story:")
print("",adperson,"",person," happened to be ",verb," the ",adjective," ",noun, ". Then ",pronoun, " ",verb2," and ",verb3, " .") 